# Fichier render.yaml

services:
- type: web # <-- DOIT AVOIR LE TIRETS ET L'INDENTATION EXACTE
  name: mon-cv-web-faton
  plan: free
  rootDir: ./ 
  env: python
  
  # Exécuter le script de base de données avant le lancement
  buildCommand: |
    pip install -r requirements.txt
    python database.py

  # CORRECTION CRUCIALE : Démarrer Gunicorn sur le port $PORT (8080)
  startCommand: gunicorn --bind 0.0.0.0:$PORT app:app 
  
  envVars:
    - key: PORT
      value: "8080"