# Blueprint pour configurer et déployer l'application CV sur Render
services:
- type: web
  name: mon-cv-web-faton
  plan: free
  rootDir: ./ 
  env: python
  
  # CORRECTION MAJEURE : Exécuter le script de base de données avant le lancement
  buildCommand: |
    pip install -r requirements.txt
    python database.py

  # Lancement de l'application (maintenant que la DB est garantie d'exister)
  startCommand: gunicorn app:app
  
  envVars:
    - key: PORT
      value: "8080"